### ISSUE TITLE
FCModel use with an encypted database and FMDB/SQLCipher

### ISSUE THREAD

**Issue by dennissterzenbach** [marcoarment/FCModel#117]
Hi,

first of all: thanks for FCModel! I really like your approach, because it is so lightweight and straight forward to use. Now my issue: I am implementing an iOS app which requires a fully encrypted database. So I started using FMDB/SQLCipher with FCModel: FCModel -> FMDB/SQLCipher -> encrypted sqlite database.

To enable a FMDatabase object to successfully work with an encrypted database, one needs to call
[db setKey:MyFancyEncryptionKey];
after 
[db open];

FCModel implements openDatabaseAtPath: methods, which give me the API to open the database easily. But unfortunately I couldn't get FCModel to work with an encrypted database via FMDB/SQLCipher without customizing openDatabaseAtPath:withDatabaseInitializer:schemaBuilder:, which breaks the ability to use FCModel with CocoaPods and means I am forking your implementation.

What are your thoughts on that?
How would you use FCModel with an encrypted database (over FMDB/SQLCipher)?
If you would like, I could contribute my implementation.

I’m really looking forward hearing from you!

Best Regards,
Dennis

**Comment by johncblandii** [comment]
Here's how I've done in before:

```objective-c
    NSString secureKey = @"awesomepassword";
    BOOL dbExists = [[NSFileManager defaultManager] fileExistsAtPath:databasePath];

    if (!dbExists) {
        sqlite3 *db;
        if (sqlite3_open([databasePath UTF8String], &db) == SQLITE_OK) {
            const char* key = [secureKey UTF8String];
            sqlite3_key(db, key, (int)strlen(key));
            if (sqlite3_exec(db, (const char*) "SELECT count(*) FROM sqlite_master;", NULL, NULL, NULL) == SQLITE_OK) {
                // password is correct, or, database has been initialized
            } else {
                // encryption failed
            }

            sqlite3_close(db);
        }
    }
    
    [FCModel openDatabaseAtPath:databasePath
            withDatabaseInitializer:^(FMDatabase *db) {
                [db setKey:secureKey];
            }
                      schemaBuilder:^(FMDatabase *db, int *schemaVersion) {
                          // Do your thing
                      }];
```

**Comment by dennissterzenbach** [comment]
Hey, 
nice one! Looks like I have overseen the option of using the initializer.

Thanks a lot for that!

**Comment by johncblandii** [comment]
No problem sir. I hope it works out.

**Comment by dennissterzenbach** [comment]
Yep, seems to work fine.
