### ISSUE TITLE
#FCReloadConflict

### ISSUE THREAD

**Issue by PrathmK** [marcoarment/FCModel#119]
While deleting from db i am get exception  'FCReloadConflict',cannot resolve conflict for (#filedname), can anyone give a little more detail about the error and how to solve it

**Comment by googler2013** [comment]
Hi Prathm,

I am getting same error, can you please help me how you are solve that issue.

Thanks

**Comment by PrathmK** [comment]
Check your classes once and the fields names that you have assigned, i was having a issue over there or if not workout send me the files , will try to look into it.
