### ISSUE TITLE
Multi-thread usage

### ISSUE THREAD

**Issue by dustturtle** [marcoarment/FCModel#143]
If I have a long long record, I will be happy to do the database action on background threads in order to have no blocking with UI. 
BUT FCModel says :"FCModels can be used from any thread, but all database reads and writes are serialized onto the main thread, so you're not likely to see any performance gains by concurrent access."
What does this mean?  
Thank you very much! need your help.

**Comment by tedrog36** [comment]
Having looked at the code in detail for the issue/question I posted yesterday, (https://github.com/marcoarment/FCModel/issues/142) I think I can answer this for you.
All database requests are made on the main UI thread using dispatch_async.  This means you cannot take advantage of performance gains of having multiple threads, for example, read/write from/to the database at the same time. (see fcm_onMainThread inline method in source code)

**Comment by dustturtle** [comment]
Thank you ! I see the fcm_onMainThread and invokes around it. I think that means we can not benifit from databasequeue (fmdb supported, with it we can do actions on background threads then no blocking with UI). I will NOT use FCModel in my app (large numbers of data, sql execution may be slow) . 
Do you agree with me?

**Comment by marcoarment** [comment]
That’s correct. FCModel is not designed for interactive use during long-running queries, so it’s probably not a good fit for your needs.

**Comment by dustturtle** [comment]
Thanks a lot!  FCModel is great for it's simple & easy to use. I will try this in other scenes.
