### ISSUE TITLE
Add multiple-database support

### ISSUE THREAD

**Issue by hartbit** [marcoarment/FCModel#43]
The way it works right now, FCModel is implemented as a bunch of class methods, relying on private global variables. It's kind of convenient, but not as flexible as I'd like. This has caused me a few issues when I wanted to open more than one database at once (for example).

Wouldn't it be more flexible to separate the library into `FCModel`, the subclass of all database table/classes, and a `FCDatabase` or `FCManager`, that handles the connection to one database?

**Comment by paventuri** [comment]
+1

I have a database using SQLCipher and a General database.

It would be perfect to have FCModel supporting multiple-database.
