### ISSUE TITLE
Unsaved results before any model access

### ISSUE THREAD

**Issue by jasonsilberman** [marcoarment/FCModel#67]
Before I even access any models, I get this error as I create the database schema:

```
FCModelDatabaseQueue has an open FMResultSet after inDatabase:
```

Why would this happen before I use any models?

Thanks!

**Comment by xieweizhi** [comment]
@jasonsilberman  hey Jason, how did you solve this problem ?

**Comment by Codeglee** [comment]
I've just updated from Swift 2.1 to Swift 3 and I'm getting this issue too. I'd really like to know how you fixed this @jasonsilberman.
