### ISSUE TITLE
closeDatabase causes crash when g_instancesReadLock hasn't been initalized

### ISSUE THREAD

**Issue by lynns** [marcoarment/FCModel#79]
I have unit tests that are crashing after the test runs when it calls `[FCModel closeDatabase]`.  The crash happens on the following line:

```
    dispatch_semaphore_wait(g_instancesReadLock, DISPATCH_TIME_FOREVER);
```

The crash occurs because the `g_instancesReadLock` variable is nil.  If in my test I do something that triggers the `uniqueMapInit` class method which in turn initializes this variable then the closeDatabase call works fine.  Is there a better place to initialize this variable so closeDatabase always works?

**Comment by googler2013** [comment]
Hello All,

I think this will  be work for this crash.

    if ([FCModel databaseIsOpen]) {
        [FCModel closeDatabase];
    }

Thanks.
